# Generated by Django 4.0.1 on 2022-01-13 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxes',
            name='date_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
